mam in progress
psi-im/iris pull request #59
Opened 2019-04-12 14:20 UTC by liuch

2019-04-12 19:15 UTC, Ri0n commented on src/xmpp/xmpp-im/types.cpp
> +Jid Message::displayJid() const
please add a comment explaining why it was added.

2019-04-12 19:19 UTC, Ri0n commented on src/xmpp/xmpp-im/types.cpp
> +void Message::setCarbonsPrivate(bool privare)
typo

2019-04-12 19:26 UTC, Ri0n commented on src/xmpp/xmpp-im/xmpp_carbons.cpp
> +static const QLatin1String xmlns_carbons("urn:xmpp:carbons:2");
probably QStringLiteral fit better here

2019-04-12 22:08 UTC, pasnox requested changes

2019-04-12 22:08 UTC, pasnox commented on src/xmpp/xmpp-im/xmpp_tasks.cpp
> +    QList<Private::SubsData> list = d->subsData.value(key);
You are modifying a copy that would detach on append and cause memory reallocations.
Just use a iterator again for the check.
Then append in this iterator value is it's valid, else call d->subsData.insert(key, {{ sbs, userData }});

2019-04-12 22:08 UTC, pasnox commented on src/xmpp/xmpp-im/xmpp_tasks.cpp
> +    QList<Private::SubsData> list = d->subsData.value(key);
This code is plain wrong.
It remove entries from a temporary list, but the original list is not updated.
Use an iterator and loop it.value() entries to remove them.
Then if it's empty, you can easily remove it with d->subsData.erase(iterator)

2019-04-13 11:30 UTC, Ri0n commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +    msg_.reset(new Message(msg));
all this mixing of smart and regular pointers look so weird. I believe if would be much better to introduce NULL Message concept when Private data is not allocated for the message.
Then regular assignment `msg_ = msg` will be enough.
I'll add relevant changes to the Message class.

2019-04-13 13:25 UTC, Ri0n commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +    msg_.reset(new Message(msg));
pushed

2019-04-13 22:09 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_carbons.cpp
> +static const QLatin1String xmlns_carbons("urn:xmpp:carbons:2");
Agree. Done.

2019-04-13 22:10 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_carbons.cpp
> +    iq = createIQ(doc(), QLatin1String("set"), QString::null, id());
I didn't know that. Done.

2019-04-21 16:56 UTC, pasnox requested changes
Nearly all QLatin1String usages are plain wrong here.
QLatin1String make sense only if the api you will use has an overload taking a QLatin1String in plus to a QString overload.
If there is only QString parameters and you know you only deal with latin 1 content then just use QString::fromLatin1() then.

2019-04-21 16:56 UTC, pasnox commented on src/xmpp/xmpp-im/xmpp_carbons.cpp
> +        if (e.attribute(QLatin1String("type")) != QLatin1String("result"))
There is no QLatin1String variant for QDN::attribute() so it's waonas you domore allocations.
Use QString::fromLatin1("...")

2019-04-21 16:56 UTC, pasnox commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +    QDomElement e = stream->doc().createElement(QLatin1String("forwarded"));
There is no QDomNode::createElement() taking a QLatin1String, so it's useless as you make 2 allocations, one for QLatin1String and one for QString, just use QString::fromLatin1("...") then.

2019-04-23 01:49 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +                msg_ = std::move(msg);
no longer relevant

2019-04-23 01:49 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +        d->sbs.release();
Probably it was autocompletion. Thanks.

2019-04-23 01:50 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +            ts_.isNull();
fixed

2019-04-23 01:51 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +{
Oh, yes. I forgot that.

2019-04-23 01:52 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_forwarding.cpp
> +void Forwarding::setTimeStamp(QDateTime ts)
Ofcourse.

2019-04-23 01:54 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_carbons.cpp
> +    }
That was unnecessary check. I removed it.

2019-04-23 01:55 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_tasks.cpp
> +        return QString("%1&%2").arg(s1).arg(s2);
Fixed. Thanks.

2019-04-23 01:56 UTC, liuch commented on src/xmpp/xmpp-im/xmpp_tasks.cpp
> +        if (subsData.contains(key)) {
You are right. Fixed.

2021-05-03 20:28 UTC, Neustradamus commented
It will be merged one day?

2023-01-08 23:38 UTC, Neustradamus commented
I think it will be nice to add this in the Google Summer of Code 2023:
- https://wiki.xmpp.org/web/Google_Summer_of_Code_2023

2024-09-28 13:07 UTC, Neustradamus commented
@Ri0n: What is missing to have the feature now? After the good work from @mcneb10?

2024-09-29 16:17 UTC, merged

2024-11-10 04:49 UTC, Neustradamus commented
A new XEP-0313 version has been released - 1.1.2 (2024-09-18):
- https://xmpp.org/extensions/xep-0313.html
- https://www5.aptest.com/standards/htmldiff/htmldiff.pl?oldfile=https://xmpp.org/extensions/attic/xep-0313-1.1.1.html&newfile=https://xmpp.org/extensions/attic/xep-0313-1.1.2.html

It is good?

Linked to:
- https://github.com/psi-im/iris/pull/73
- https://github.com/psi-im/psi/issues/62

2025-08-21 22:55 UTC, Neustradamus commented
Since the good work done by @mcneb10:
- https://github.com/psi-im/iris/pull/73

And after XEP-0313 1.1.2 (2024-09-18), a new XEP-0313 version has been released - 1.1.3 (2025-04-09):
- https://xmpp.org/extensions/xep-0313.html
- https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0313-1.1.2.html&doc2=https://xmpp.org/extensions/attic/xep-0313-1.1.3.html
- https://services.w3.org/htmldiff?doc1=https://xmpp.org/extensions/attic/xep-0313-1.1.1.html&doc2=https://xmpp.org/extensions/attic/xep-0313-1.1.2.html